### ISSUE TITLE
Add links behind logos

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat-website#95]
Hi @cinaaaa,
I have some new tasks where you could assist. This time on the GOAT3.0 project website (https://www.open-accessibility.org/), which was our former "GOAT open source project website".

**GOAL** 
We would like to have the links to the institution/company websites behind their logos:
![grafik](https://github.com/goat-community/goat-website/assets/49870195/f5a3faa6-cc27-46c5-8964-d8fe0f59706e)

**TASK**
Currently, it's just an image. Would be great if you could convert it into a clickable section. These are the 5 logo files (stored in _\goat-website\uploads_) and the links: 
- "logo_ioer" - https://www.ioer.de/en/https://www.ioer.de/en/
- "logo_mvv" (they change the logo, the one on the GOAT 3.0 website is outdated) - https://www.mvv-muenchen.de/en/index.html
- "logo_p4b" - https://plan4better.de/en/
- "logo_psu" - https://www.psu-schaller.de/?l=en
- "logo_tum" - https://www.ioer.de/en/

**FURTHER INFORMATION**
Would be great to have this until 23rd of June. 
As far as I know, the website is written in Jekyll. Let me know if you have some questions, maybe I can help.

Thank you!

**Comment by cinaaaa** [comment]
@UJehle  I think the tum link is wrong here

**Comment by UJehle** [comment]
@cinaaaa : oh true! This is the right one: https://www.mos.ed.tum.de/en/sv/homepage/

**Comment by UJehle** [comment]
@majkshkurti would it be possible to shift our logo to the center? 
![grafik](https://github.com/goat-community/goat-website/assets/49870195/94eaa6d9-02b3-4244-ab63-3cfa7b179d7e)
