### ISSUE TITLE
Adjust landing screen

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat-website#96]
@cinaaaa could you implement the following changes to the landing page: 

1. making the image a bit smaller
2. placing the text above the image
3. add four buttons to the right (I think there should already be a button component that you can use), you can place a dummy link behind them, I will then set the correct paths as soon as I created the subpages

![grafik](https://github.com/goat-community/goat-website/assets/49870195/c29e2901-1fd3-4a7d-a98d-71306aab4d3a)

Would be great to also have this by the 23rd of June. Thanks a lot!

**Comment by cinaaaa** [comment]
@UJehle 

![Image](https://github.com/goat-community/goat-website/assets/42252572/2ea9c8a8-9a8f-4c72-a056-6e7a35ddc949)

Let me know in case of changing the buttons style

**Comment by UJehle** [comment]
Hi @cinaaaa, the screenshot looks okay to me. 
I am still struggeling with loading the website locally but will give it another try soon.

**Comment by UJehle** [comment]
To Do:
- adjust margin
- (if time: make buttons more 2023)

**Comment by UJehle** [comment]
Hi @majkshkurti, I got some feedback from Basti. Could you also make this section a bit smaller, so that the "What is GOAT?" heading is already visible when a person opens the website? 
![grafik](https://github.com/goat-community/goat-website/assets/49870195/7bed6bf6-14ca-4bd6-9e94-b473e5da5674)
